#############################################################################
# Makefile for building: IHM
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Feb 23 12:51:07 2014
# Project:  IHM.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile IHM.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -I. -Icore -Icore/point -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtXml -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		echelle.cpp \
		graphicsview.cpp \
		gpoint.cpp \
		core/etage.cpp \
		core/point/point.cpp \
		core/lien.cpp \
		core/parseur/parseur.cpp \
		core/point/toilette.cpp \
		core/batiment.cpp \
		core/projet.cpp \
		core/point/escalier.cpp \
		core/point/namedpoint.cpp \
		core/point/salle.cpp \
		core/point/couloir.cpp \
		core/point/namedaccessiblepoint.cpp \
		core/point/ascenseur.cpp \
		core/point/porte.cpp \
		core/point/qrcode.cpp \
		ecrituredom.cpp \
		core/point/entreesortie.cpp \
		liaison.cpp moc_mainwindow.cpp \
		moc_graphicsview.cpp \
		moc_ecrituredom.cpp
OBJECTS       = main.o \
		mainwindow.o \
		echelle.o \
		graphicsview.o \
		gpoint.o \
		etage.o \
		point.o \
		lien.o \
		parseur.o \
		toilette.o \
		batiment.o \
		projet.o \
		escalier.o \
		namedpoint.o \
		salle.o \
		couloir.o \
		namedaccessiblepoint.o \
		ascenseur.o \
		porte.o \
		qrcode.o \
		ecrituredom.o \
		entreesortie.o \
		liaison.o \
		moc_mainwindow.o \
		moc_graphicsview.o \
		moc_ecrituredom.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		IHM.pro
QMAKE_TARGET  = IHM
DESTDIR       = 
TARGET        = IHM

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: IHM.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile IHM.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile IHM.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/IHM1.0.0 || $(MKDIR) .tmp/IHM1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/IHM1.0.0/ && $(COPY_FILE) --parents mainwindow.h echelle.h graphicsview.h gpoint.h core/etage.h core/point/point.h core/lien.h core/parseur/parseur.h core/point/toilette.h core/genre.h core/batiment.h core/projet.h core/point/type_point.h core/point/escalier.h core/point/namedpoint.h core/point/salle.h core/point/couloir.h core/point/type_acces.h core/point/namedaccessiblepoint.h core/point/ascenseur.h core/point/porte.h core/point/qrcode.h ecrituredom.h core/point/entreesortie.h liaison.h .tmp/IHM1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp echelle.cpp graphicsview.cpp gpoint.cpp core/etage.cpp core/point/point.cpp core/lien.cpp core/parseur/parseur.cpp core/point/toilette.cpp core/batiment.cpp core/projet.cpp core/point/escalier.cpp core/point/namedpoint.cpp core/point/salle.cpp core/point/couloir.cpp core/point/namedaccessiblepoint.cpp core/point/ascenseur.cpp core/point/porte.cpp core/point/qrcode.cpp ecrituredom.cpp core/point/entreesortie.cpp liaison.cpp .tmp/IHM1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/IHM1.0.0/ && (cd `dirname .tmp/IHM1.0.0` && $(TAR) IHM1.0.0.tar IHM1.0.0 && $(COMPRESS) IHM1.0.0.tar) && $(MOVE) `dirname .tmp/IHM1.0.0`/IHM1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/IHM1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_graphicsview.cpp moc_ecrituredom.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_graphicsview.cpp moc_ecrituredom.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_graphicsview.cpp: core/point/type_point.h \
		core/etage.h \
		core/point/point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h \
		graphicsview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) graphicsview.h -o moc_graphicsview.cpp

moc_ecrituredom.cpp: core/etage.h \
		core/point/point.h \
		core/point/type_point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h \
		ecrituredom.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ecrituredom.h -o moc_ecrituredom.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		graphicsview.h \
		core/point/type_point.h \
		core/etage.h \
		core/point/point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		ecrituredom.h \
		core/etage.h \
		core/point/point.h \
		core/point/type_point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		echelle.h \
		graphicsview.h \
		core/point/type_point.h \
		core/etage.h \
		core/point/point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

echelle.o: echelle.cpp echelle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o echelle.o echelle.cpp

graphicsview.o: graphicsview.cpp graphicsview.h \
		core/point/type_point.h \
		core/etage.h \
		core/point/point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h \
		gpoint.h \
		echelle.h \
		liaison.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicsview.o graphicsview.cpp

gpoint.o: gpoint.cpp gpoint.h \
		graphicsview.h \
		core/point/type_point.h \
		core/etage.h \
		core/point/point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gpoint.o gpoint.cpp

etage.o: core/etage.cpp core/etage.h \
		core/point/point.h \
		core/point/type_point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o etage.o core/etage.cpp

point.o: core/point/point.cpp core/point/point.h \
		core/point/type_point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o point.o core/point/point.cpp

lien.o: core/lien.cpp core/lien.h \
		core/point/point.h \
		core/point/type_point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lien.o core/lien.cpp

parseur.o: core/parseur/parseur.cpp core/parseur/parseur.h \
		core/etage.h \
		core/point/point.h \
		core/point/type_point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parseur.o core/parseur/parseur.cpp

toilette.o: core/point/toilette.cpp core/point/toilette.h \
		core/genre.h \
		core/point/type_point.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o toilette.o core/point/toilette.cpp

batiment.o: core/batiment.cpp core/batiment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o batiment.o core/batiment.cpp

projet.o: core/projet.cpp core/projet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o projet.o core/projet.cpp

escalier.o: core/point/escalier.cpp core/point/escalier.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_point.h \
		core/point/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o escalier.o core/point/escalier.cpp

namedpoint.o: core/point/namedpoint.cpp core/point/namedpoint.h \
		core/point/type_point.h \
		core/point/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o namedpoint.o core/point/namedpoint.cpp

salle.o: core/point/salle.cpp core/point/salle.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_point.h \
		core/point/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o salle.o core/point/salle.cpp

couloir.o: core/point/couloir.cpp core/point/couloir.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_point.h \
		core/point/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o couloir.o core/point/couloir.cpp

namedaccessiblepoint.o: core/point/namedaccessiblepoint.cpp core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_point.h \
		core/point/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o namedaccessiblepoint.o core/point/namedaccessiblepoint.cpp

ascenseur.o: core/point/ascenseur.cpp core/point/ascenseur.h \
		core/point/type_point.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/point.h \
		core/point/type_acces.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ascenseur.o core/point/ascenseur.cpp

porte.o: core/point/porte.cpp core/point/porte.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_point.h \
		core/point/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o porte.o core/point/porte.cpp

qrcode.o: core/point/qrcode.cpp core/point/qrcode.h \
		core/point/namedpoint.h \
		core/point/type_point.h \
		core/point/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrcode.o core/point/qrcode.cpp

ecrituredom.o: ecrituredom.cpp ecrituredom.h \
		core/etage.h \
		core/point/point.h \
		core/point/type_point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ecrituredom.o ecrituredom.cpp

entreesortie.o: core/point/entreesortie.cpp core/point/entreesortie.h \
		core/point/namedpoint.h \
		core/point/type_point.h \
		core/point/point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o entreesortie.o core/point/entreesortie.cpp

liaison.o: liaison.cpp liaison.h \
		graphicsview.h \
		core/point/type_point.h \
		core/etage.h \
		core/point/point.h \
		core/lien.h \
		core/point/ascenseur.h \
		core/point/namedaccessiblepoint.h \
		core/point/namedpoint.h \
		core/point/type_acces.h \
		core/point/couloir.h \
		core/point/escalier.h \
		core/point/porte.h \
		core/point/qrcode.h \
		core/point/salle.h \
		core/point/toilette.h \
		core/genre.h \
		core/point/entreesortie.h \
		gpoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o liaison.o liaison.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_graphicsview.o: moc_graphicsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphicsview.o moc_graphicsview.cpp

moc_ecrituredom.o: moc_ecrituredom.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ecrituredom.o moc_ecrituredom.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

